name: supabase_phone_auth
description: A Flutter app scaffold integrated with Supabase for phone+password auth (phone converted to email)
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  supabase_flutter: ^1.0.0
  get_storage: ^2.0.3
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  image_picker: ^0.8.7+4
  cached_network_image: ^3.2.3
  google_fonts: ^3.0.1
  animations: ^2.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
